/**
 * Auto-generated by scripts/sync-shopify-variants.mjs
 * Re-run after adding products or variants in Shopify.
 */

export const shopifyHandleBySlug: Record<string, string> = {
  // No handle aliases
};

export const shopifyVariantByKey: Record<string, string> = {
  "long-tee:L": "gid://shopify/ProductVariant/58375846560128",
  "long-tee:M": "gid://shopify/ProductVariant/58375846527360",
  "long-tee:S": "gid://shopify/ProductVariant/58375846494592",
  "long-tee:XL": "gid://shopify/ProductVariant/58375846592896",
};

export function shopifyVariantKey(slug: string, size: string) {
  return `${slug}:${size}`;
}

export function resolveMerchandiseId(slug: string, size: string): string | undefined {
  const direct = shopifyVariantByKey[shopifyVariantKey(slug, size)];
  if (direct) return direct;

  const handle = shopifyHandleBySlug[slug];
  if (handle) {
    return shopifyVariantByKey[shopifyVariantKey(handle, size)];
  }

  return undefined;
}
