/**
 * Auto-generated by scripts/sync-shopify-variants.mjs
 * Re-run after adding products or variants in Shopify.
 */

export const shopifyHandleBySlug: Record<string, string> = {
  "carpenter-pant": "capsule-v1",
  "coach-jacket": "capsule-v1",
  "heavy-hoodie": "capsule-v1",
  "heavyweight-crew": "capsule-v1",
  "long-sleeve": "capsule-v1",
  "long-sleeve-black": "capsule-v1",
  "long-tee": "capsule-v1",
  "long-tee-black": "capsule-v1",
  "tall-tank": "capsule-v1",
  "wide-trouser": "capsule-v1",
  "wide-trouser-black": "capsule-v1",
  "zip-hoodie": "capsule-v1",
};

export const shopifyVariantByKey: Record<string, string> = {
  "capsule-v1:S": "gid://shopify/ProductVariant/58270536270208",
  "capsule-v1:XL": "gid://shopify/ProductVariant/58270530175360",
  "coach-jacket:XL": "gid://shopify/ProductVariant/58270530175360",
  "heavy-hoodie:XL": "gid://shopify/ProductVariant/58270530175360",
  "heavyweight-crew:XL": "gid://shopify/ProductVariant/58270530175360",
  "long-sleeve-black:XL": "gid://shopify/ProductVariant/58270530175360",
  "long-sleeve:XL": "gid://shopify/ProductVariant/58270530175360",
  "long-tee-black:XL": "gid://shopify/ProductVariant/58270530175360",
  "long-tee:XL": "gid://shopify/ProductVariant/58270530175360",
  "tall-tank:XL": "gid://shopify/ProductVariant/58270530175360",
  "zip-hoodie:XL": "gid://shopify/ProductVariant/58270530175360",
};

export function shopifyVariantKey(slug: string, size: string) {
  return `${slug}:${size}`;
}

export function resolveMerchandiseId(slug: string, size: string): string | undefined {
  const direct = shopifyVariantByKey[shopifyVariantKey(slug, size)];
  if (direct) return direct;

  const handle = shopifyHandleBySlug[slug];
  if (handle) {
    return shopifyVariantByKey[shopifyVariantKey(handle, size)];
  }

  return undefined;
}
